sonar.projectKey=elix-star-live
sonar.projectName=Elix Star Live
sonar.sources=src,server
sonar.exclusions=**/node_modules/**,**/dist/**,**/android/**,**/ios/**,**/docs/**,**/tools/**,**/*.test.ts,**/*.test.tsx
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=
