-- Seed full Bunny gifts catalog (45 gifts).
BEGIN;

INSERT INTO elix_gifts (gift_id, name, gift_type, coin_cost, animation_url, sfx_url, is_active, battle_points) VALUES
  ('horse', 'Horse', 'small', 15, '/gifts/Horse.mp4', NULL, TRUE, 15),
  ('ember_dragon_egg', 'Ember Dragon Egg', 'small', 25, '/gifts/ember_dragon_egg.mp4', NULL, TRUE, 25),
  ('frost_wolf', 'Frost Wolf', 'small', 35, '/gifts/frost_wolf.mp4', NULL, TRUE, 35),
  ('rex_dinosaur', 'Rex Dinosaur', 'small', 50, '/gifts/rex_dinosaur.mp4', NULL, TRUE, 50),
  ('night_panther', 'Night Panther', 'small', 75, '/gifts/night_panther.mp4', NULL, TRUE, 75),
  ('stormborn_night_owl', 'Stormborn Night Owl', 'small', 100, '/gifts/stormborn_night_owl.mp4', NULL, TRUE, 100),
  ('treasure_drake_cub', 'Treasure Drake Cub', 'small', 125, '/gifts/treasure_drake_cub.mp4', NULL, TRUE, 125),
  ('pink_love_jet', 'Pink Love Jet', 'small', 150, '/gifts/pink_love_jet.mp4', NULL, TRUE, 150),
  ('romantic_jet', 'Romantic Jet', 'small', 175, '/gifts/romantic_jet.mp4', NULL, TRUE, 175),
  ('beast_relic_of_the_ancients', 'Beast Relic Of The Ancients', 'small', 200, '/gifts/beast_relic_of_the_ancients.webm', NULL, TRUE, 200),
  ('elix_ice_sorceress', 'Elix Ice Sorceress', 'big', 250, '/gifts/elix_ice_sorceress.mp4', NULL, TRUE, 1250),
  ('lightning_hypercar', 'Lightning Hypercar', 'big', 250, '/gifts/lightning_hypercar.mp4', NULL, TRUE, 1250),
  ('a_gleaming_treasure_chest_in_a_cave', 'A Gleaming Treasure Chest In A Cave', 'big', 350, '/gifts/a_gleaming_treasure_chest_in_a_cave.mp4', NULL, TRUE, 1750),
  ('celestial_star_wand', 'Celestial Star Wand', 'big', 350, '/gifts/celestial_star_wand.mp4', NULL, TRUE, 1750),
  ('crown_kitty_treasure', 'Crown Kitty Treasure', 'big', 350, '/gifts/crown_kitty_treasure.mp4', NULL, TRUE, 1750),
  ('crystal_rhino', 'Crystal Rhino', 'big', 350, '/gifts/crystal_rhino.mp4', NULL, TRUE, 1750),
  ('crystal_voyager_ship', 'Crystal Voyager Ship', 'big', 350, '/gifts/crystal_voyager_ship.mp4', NULL, TRUE, 1750),
  ('elix_thunder_falcon', 'Elix Thunder Falcon', 'big', 350, '/gifts/elix_thunder_falcon.mp4', NULL, TRUE, 1750),
  ('fantasy_celestial_war_bird', 'Fantasy Celestial War Bird', 'big', 350, '/gifts/fantasy_celestial_war_bird.mp4', NULL, TRUE, 1750),
  ('fantasy_unicorn', 'Fantasy Unicorn', 'big', 350, '/gifts/fantasy_unicorn.mp4', NULL, TRUE, 1750),
  ('ferocious_wolf_in_misty_terrain', 'Ferocious Wolf In Misty Terrain', 'big', 350, '/gifts/ferocious_wolf_in_misty_terrain.mp4', NULL, TRUE, 1750),
  ('fiery_lion_in_blazing_glory', 'Fiery Lion In Blazing Glory', 'big', 350, '/gifts/fiery_lion_in_blazing_glory.mp4', NULL, TRUE, 1750),
  ('fiery_power_of_the_blazing_wizard', 'Fiery Power Of The Blazing Wizard', 'big', 350, '/gifts/fiery_power_of_the_blazing_wizard.mp4', NULL, TRUE, 1750),
  ('golden_rage_lion', 'Golden Rage Lion', 'big', 350, '/gifts/golden_rage_lion.mp4', NULL, TRUE, 1750),
  ('aelyra_flameveil', 'Aelyra Flameveil', 'big', 500, '/gifts/aelyra_flameveil.mp4', NULL, TRUE, 2500),
  ('arcane_storm_phoenix', 'Arcane Storm Phoenix', 'big', 500, '/gifts/arcane_storm_phoenix.mp4', NULL, TRUE, 2500),
  ('cosmic_panther', 'Cosmic Panther', 'big', 500, '/gifts/cosmic_panther.mp4', NULL, TRUE, 2500),
  ('dragon_s_wrath_ride', 'Dragon S Wrath Ride', 'big', 500, '/gifts/dragon_s_wrath_ride.mp4', NULL, TRUE, 2500),
  ('earth_titan_gorilla', 'Earth Titan Gorilla', 'big', 500, '/gifts/earth_titan_gorilla.mp4', NULL, TRUE, 2500),
  ('eternal_guardian', 'Eternal Guardian', 'big', 500, '/gifts/eternal_guardian.mp4', NULL, TRUE, 2500),
  ('fire_phoenix', 'Fire Phoenix', 'big', 500, '/gifts/fire_phoenix.mp4', NULL, TRUE, 2500),
  ('flames_and_royalty_on_fiery_ground', 'Flames And Royalty On Fiery Ground', 'big', 500, '/gifts/flames_and_royalty_on_fiery_ground.mp4', NULL, TRUE, 2500),
  ('froststorm_lion', 'Froststorm Lion', 'big', 500, '/gifts/froststorm_lion.mp4', NULL, TRUE, 2500),
  ('infernal_lion_king', 'Infernal Lion King', 'big', 500, '/gifts/infernal_lion_king.mp4', NULL, TRUE, 2500),
  ('lava_demon', 'Lava Demon', 'big', 500, '/gifts/lava_demon.mp4', NULL, TRUE, 2500),
  ('lavarok', 'Lavarok', 'big', 500, '/gifts/lavarok.mp4', NULL, TRUE, 2500),
  ('legendary_guardians_of_treasure_chest', 'Legendary Guardians Of Treasure Chest', 'big', 500, '/gifts/legendary_guardians_of_treasure_chest.mp4', NULL, TRUE, 2500),
  ('majestic_ice_blue_mythic_bird', 'Majestic Ice Blue Mythic Bird', 'big', 500, '/gifts/majestic_ice_blue_mythic_bird.mp4', NULL, TRUE, 2500),
  ('majestic_phoenix_soaring_in_flames', 'Majestic Phoenix Soaring In Flames', 'big', 500, '/gifts/majestic_phoenix_soaring_in_flames.mp4', NULL, TRUE, 2500),
  ('molten_fury_of_the_lava_dragon', 'Molten Fury Of The Lava Dragon', 'big', 500, '/gifts/molten_fury_of_the_lava_dragon.mp4', NULL, TRUE, 2500),
  ('mythic_beast_vault_phoenix_lion_dragon_bear_wolf', 'Mythic Beast Vault Phoenix Lion Dragon Bear Wolf', 'big', 500, '/gifts/mythic_beast_vault_phoenix_lion_dragon_bear_wolf.mp4', NULL, TRUE, 2500),
  ('mythic_fire_unicorn', 'Mythic Fire Unicorn', 'big', 500, '/gifts/mythic_fire_unicorn.mp4', NULL, TRUE, 2500),
  ('rampage_of_the_lava_beast', 'Rampage Of The Lava Beast', 'big', 500, '/gifts/rampage_of_the_lava_beast.mp4', NULL, TRUE, 2500),
  ('storm_warrior_in_electric_fury', 'Storm Warrior In Electric Fury', 'big', 500, '/gifts/storm_warrior_in_electric_fury.mp4', NULL, TRUE, 2500),
  ('the_flame_king', 'The Flame King', 'big', 500, '/gifts/the_flame_king.mp4', NULL, TRUE, 2500)
ON CONFLICT (gift_id) DO UPDATE SET
  name = EXCLUDED.name,
  gift_type = EXCLUDED.gift_type,
  coin_cost = EXCLUDED.coin_cost,
  animation_url = EXCLUDED.animation_url,
  is_active = EXCLUDED.is_active,
  battle_points = EXCLUDED.battle_points;

COMMIT;
