-- Sync elix_gifts with Bunny Storage /gifts/ inventory (48 video files, verified 2026-08-04).
-- App loads catalog from DB (GET /api/gifts/catalog). Idempotent upsert — safe to re-run.
BEGIN;

INSERT INTO elix_gifts (gift_id, name, gift_type, coin_cost, animation_url, sfx_url, is_active, battle_points) VALUES
  ('horse', 'Horse', 'small', 5000, '/gifts/Horse.mp4', NULL, TRUE, 5000),
  ('ember_dragon_egg', 'Ember Dragon Egg', 'small', 5500, '/gifts/ember_dragon_egg.mp4', NULL, TRUE, 5500),
  ('frost_wolf', 'Frost Wolf', 'small', 6000, '/gifts/frost_wolf.mp4', NULL, TRUE, 6000),
  ('rex_dinosaur', 'Rex Dinosaur', 'small', 7500, '/gifts/rex_dinosaur.mp4', NULL, TRUE, 7500),
  ('night_panther', 'Night Panther', 'small', 8000, '/gifts/night_panther.mp4', NULL, TRUE, 8000),
  ('stormborn_night_owl', 'Stormborn Night Owl', 'small', 9000, '/gifts/stormborn_night_owl.mp4', NULL, TRUE, 9000),
  ('treasure_drake_cub', 'Treasure Drake Cub', 'small', 9500, '/gifts/treasure_drake_cub.mp4', NULL, TRUE, 9500),
  ('pink_love_jet', 'Pink Love Jet', 'big', 50000, '/gifts/pink_love_jet.mp4', NULL, TRUE, 250000),
  ('romantic_jet', 'Romantic Jet', 'small', 11000, '/gifts/romantic_jet.mp4', NULL, TRUE, 11000),
  ('beast_relic_of_the_ancients', 'Beast Relic Of The Ancients', 'small', 12000, '/gifts/beast_relic_of_the_ancients.webm', NULL, TRUE, 12000),
  ('elix_ice_sorceress', 'Elix Ice Sorceress', 'big', 14000, '/gifts/elix_ice_sorceress.mp4', NULL, TRUE, 70000),
  ('lightning_hypercar', 'Lightning Hypercar', 'big', 15000, '/gifts/lightning_hypercar.mp4', NULL, TRUE, 75000),
  ('a_gleaming_treasure_chest_in_a_cave', 'A Gleaming Treasure Chest In A Cave', 'big', 17000, '/gifts/a_gleaming_treasure_chest_in_a_cave.mp4', NULL, TRUE, 85000),
  ('celestial_star_wand', 'Celestial Star Wand', 'big', 18000, '/gifts/celestial_star_wand.mp4', NULL, TRUE, 90000),
  ('crown_kitty_treasure', 'Crown Kitty Treasure', 'big', 19000, '/gifts/crown_kitty_treasure.mp4', NULL, TRUE, 95000),
  ('crystal_rhino', 'Crystal Rhino', 'big', 20000, '/gifts/crystal_rhino.mp4', NULL, TRUE, 100000),
  ('crystal_voyager_ship', 'Crystal Voyager Ship', 'big', 21000, '/gifts/crystal_voyager_ship.mp4', NULL, TRUE, 105000),
  ('elix_thunder_falcon', 'Elix Thunder Falcon', 'big', 22000, '/gifts/elix_thunder_falcon.mp4', NULL, TRUE, 110000),
  ('fantasy_celestial_war_bird', 'Fantasy Celestial War Bird', 'big', 23000, '/gifts/fantasy_celestial_war_bird.mp4', NULL, TRUE, 115000),
  ('fantasy_unicorn', 'Fantasy Unicorn', 'big', 24000, '/gifts/fantasy_unicorn.mp4', NULL, TRUE, 120000),
  ('ferocious_wolf_in_misty_terrain', 'Ferocious Wolf In Misty Terrain', 'big', 25000, '/gifts/ferocious_wolf_in_misty_terrain.mp4', NULL, TRUE, 125000),
  ('fiery_lion_in_blazing_glory', 'Fiery Lion In Blazing Glory', 'big', 26000, '/gifts/fiery_lion_in_blazing_glory.mp4', NULL, TRUE, 130000),
  ('fiery_power_of_the_blazing_wizard', 'Fiery Power Of The Blazing Wizard', 'big', 27000, '/gifts/fiery_power_of_the_blazing_wizard.mp4', NULL, TRUE, 135000),
  ('golden_rage_lion', 'Golden Rage Lion', 'big', 28000, '/gifts/golden_rage_lion.mp4', NULL, TRUE, 140000),
  ('aelyra_flameveil', 'Aelyra Flameveil', 'big', 30000, '/gifts/aelyra_flameveil.mp4', NULL, TRUE, 150000),
  ('arcane_storm_phoenix', 'Arcane Storm Phoenix', 'big', 31000, '/gifts/arcane_storm_phoenix.mp4', NULL, TRUE, 155000),
  ('cosmic_panther', 'Cosmic Panther', 'big', 32000, '/gifts/cosmic_panther.mp4', NULL, TRUE, 160000),
  ('dragon_s_wrath_ride', 'Dragon S Wrath Ride', 'big', 33000, '/gifts/dragon_s_wrath_ride.mp4', NULL, TRUE, 165000),
  ('earth_titan_gorilla', 'Earth Titan Gorilla', 'big', 34000, '/gifts/earth_titan_gorilla.mp4', NULL, TRUE, 170000),
  ('eternal_guardian', 'Eternal Guardian', 'big', 35000, '/gifts/eternal_guardian.mp4', NULL, TRUE, 175000),
  ('fire_phoenix', 'Fire Phoenix', 'big', 36000, '/gifts/fire_phoenix.mp4', NULL, TRUE, 180000),
  ('flames_and_royalty_on_fiery_ground', 'Flames And Royalty On Fiery Ground', 'big', 37000, '/gifts/flames_and_royalty_on_fiery_ground.mp4', NULL, TRUE, 185000),
  ('froststorm_lion', 'Froststorm Lion', 'big', 38000, '/gifts/froststorm_lion.mp4', NULL, TRUE, 190000),
  ('infernal_lion_king', 'Infernal Lion King', 'big', 39000, '/gifts/infernal_lion_king.mp4', NULL, TRUE, 195000),
  ('lava_demon', 'Lava Demon', 'big', 40000, '/gifts/lava_demon.mp4', NULL, TRUE, 200000),
  ('lavarok', 'Lavarok', 'big', 41000, '/gifts/lavarok.mp4', NULL, TRUE, 205000),
  ('legendary_guardians_of_treasure_chest', 'Legendary Guardians Of Treasure Chest', 'big', 42000, '/gifts/legendary_guardians_of_treasure_chest.mp4', NULL, TRUE, 210000),
  ('majestic_ice_blue_mythic_bird', 'Majestic Ice Blue Mythic Bird', 'big', 43000, '/gifts/majestic_ice_blue_mythic_bird.mp4', NULL, TRUE, 215000),
  ('majestic_phoenix_soaring_in_flames', 'Majestic Phoenix Soaring In Flames', 'big', 44000, '/gifts/majestic_phoenix_soaring_in_flames.mp4', NULL, TRUE, 220000),
  ('molten_fury_of_the_lava_dragon', 'Molten Fury Of The Lava Dragon', 'big', 45000, '/gifts/molten_fury_of_the_lava_dragon.mp4', NULL, TRUE, 225000),
  ('mythic_beast_vault_phoenix_lion_dragon_bear_wolf', 'Mythic Beast Vault Phoenix Lion Dragon Bear Wolf', 'big', 46000, '/gifts/mythic_beast_vault_phoenix_lion_dragon_bear_wolf.mp4', NULL, TRUE, 230000),
  ('mythic_fire_unicorn', 'Mythic Fire Unicorn', 'big', 47000, '/gifts/mythic_fire_unicorn.mp4', NULL, TRUE, 235000),
  ('rampage_of_the_lava_beast', 'Rampage Of The Lava Beast', 'big', 48000, '/gifts/rampage_of_the_lava_beast.mp4', NULL, TRUE, 240000),
  ('storm_warrior_in_electric_fury', 'Storm Warrior In Electric Fury', 'big', 48500, '/gifts/storm_warrior_in_electric_fury.mp4', NULL, TRUE, 242500),
  ('the_flame_king', 'The Flame King', 'big', 49000, '/gifts/the_flame_king.mp4', NULL, TRUE, 245000),
  ('elix_live_universe', 'Elix Live', 'universe', 49500, '/gifts/elix_live_universe.webm', NULL, TRUE, 49500),
  ('elix_gold_universe', 'Elix Gold', 'universe', 49800, '/gifts/elix_gold_universe.webm', NULL, TRUE, 49800),
  ('elix_global_universe', 'Elix Universe', 'universe', 49900, '/gifts/elix_global_universe.webm', NULL, TRUE, 49900)
ON CONFLICT (gift_id) DO UPDATE SET
  name = EXCLUDED.name,
  gift_type = EXCLUDED.gift_type,
  coin_cost = EXCLUDED.coin_cost,
  animation_url = EXCLUDED.animation_url,
  is_active = EXCLUDED.is_active,
  battle_points = EXCLUDED.battle_points;

COMMIT;
